version: "3"

services:
  app:
    container_name: django-api-example
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: django-api-example-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  backend:

volumes:
  postgres:
