openapi: 3.0.3

info:
  title: Article API
  description: API for managing articles.
  version: 1.0.0

servers:
  - url: "http://localhost:8000"
    description: Local development server on port 8000

security:
  - jwt: []

paths:
  "/api/articles":
    get:
      tags: ["articles"]
      summary: Returns all articles
      security:
        - jwt: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/article"
    post:
      tags: ["articles"]
      summary: Create a new article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        "201":
          description: Article created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/article"

  "/api/articles/{id}":
    get:
      tags: ["articles"]
      summary: Retrieve an article by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the article to retrieve
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/article"
        "404":
          description: Article not found

    put:
      tags: ["articles"]
      summary: Update an article by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the article to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        "200":
          description: Article updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/article"
        "404":
          description: Article not found

    delete:
      tags: ["articles"]
      summary: Delete an article by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the article to delete
      responses:
        "204":
          description: Article deleted successfully
        "404":
          description: Article not found

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    article:
      type: object
      properties:
        id:
          type: integer
          description: ID of the article
        title:
          type: string
          description: Title of the article
